{% set name = "x-wr-timezone" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/x_wr_timezone-{{ version }}.tar.gz
  sha256: 9166c40e6ffd4c0edebabc354e1a1e2cffc1bb473f88007694793757685cc8c3

build:
  entry_points:
    - x-wr-timezone = x_wr_timezone:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - python-tzdata
  run:
    - python >={{ python_min }}
    - icalendar >=6.1.0
    - python-tzdata
    - click

test:
  imports:
    - x_wr_timezone
  commands:
    - pip check
    - x-wr-timezone --help
  requires:
    - python {{ python_min }}
    - pip
    - python-tzdata
    - icalendar >=6.1.0

about:
  home: https://github.com/niccokunzmann/x-wr-timezone
  summary: Repair Google Calendar - This Python module and program makes ICS/iCalendar files using X-WR-TIMEZONE compatible with the RFC 5545 standard.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
