{% set name = "x-wr-timezone" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/x_wr_timezone-{{ version }}.tar.gz
  sha256: 0a5e20c603c0876b03b6ce3b8682c69c18da8ca107aec70caefa58a8f396bf48

build:
  entry_points:
    - x-wr-timezone = x_wr_timezone:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - icalendar
    - pytz

test:
  imports:
    - x_wr_timezone
  commands:
    - pip check
    - x-wr-timezone --help
  requires:
    - pip

about:
  home: https://github.com/niccokunzmann/x-wr-timezone
  summary: A Python module and program to convert calendars using X-WR-TIMEZONE to standard ones.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
