{% set name = "x-wr-timezone" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/x_wr_timezone-{{ version }}.tar.gz
  sha256: 1e475d2dedcd2128550cd88b4b5773a224e936e1c9f22ff50104622180455265

build:
  entry_points:
    - x-wr-timezone = x_wr_timezone:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
    - python-tzdata
  run:
    - python >=3.9
    - icalendar
    - python-tzdata

test:
  imports:
    - x_wr_timezone
  commands:
    - pip check
    - x-wr-timezone --help
  requires:
    - pip
    - python-tzdata
    - icalendar

about:
  home: https://github.com/niccokunzmann/x-wr-timezone
  summary: A Python module and program to convert calendars using X-WR-TIMEZONE to standard ones.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
