{% set name = "x-wr-timezone" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/x_wr_timezone-{{ version }}.tar.gz
  sha256: 720fb58275c450f9563deaa1118c69ecdcad70874e9c0b4a23dcb2c10584af80

build:
  entry_points:
    - x-wr-timezone = x_wr_timezone:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - icalendar
    - tzdata

test:
  imports:
    - x_wr_timezone
  commands:
    - pip check
    - x-wr-timezone --help
  requires:
    - pip

about:
  home: https://github.com/niccokunzmann/x-wr-timezone
  summary: A Python module and program to convert calendars using X-WR-TIMEZONE to standard ones.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
